# traefik.toml
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

# listen on port 80
[entryPoints]
  [entryPoints.web]
    address = ":80"

# Traefik dashboard over http
[api]
  dashboard = true
  insecure = true

[log]
  level = "ERROR"
  filePath = "log/traefik.log"
  format = "json"

[accessLog]
  filePath = "accesslog/access.log"
  format = "json"

# containers are not discovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false

[ping]
  entryPoint = "traefik"